name: Build PDF DOOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Clone and setup Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git --branch 1.39.20
        ./emsdk/emsdk install 1.39.20-fastcomp
        ./emsdk/emsdk activate 1.39.20-fastcomp
        source ./emsdk/emsdk_env.sh

    - name: Download DOOM WAD
      run: |
        wget "https://distro.ibiblio.org/slitaz/sources/packages/d/doom1.wad" -O "doomgeneric/doom1.wad"

    - name: Build
      run: |
        source .venv/bin/activate
        source ./emsdk/emsdk_env.sh
        emmake make -C doomgeneric -f Makefile.pdfjs -j$(nproc --all)
        
        mkdir -p out
        cp web/* out/
        
        python3 embed_file.py file_template.js doomgeneric/doom1.wad out/data.js
        cat pre.js out/data.js doomgeneric/doomgeneric.js > out/compiled.js
        cat pre.js file_template.js doomgeneric/doomgeneric.js > out/compiled_nowad.js
        
        python3 generate.py out/compiled.js out/doom.pdf
        python3 generate.py out/compiled_nowad.js out/doom_nowad.pdf

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdf-doom
        path: |
          out/doom.pdf
          out/doom_nowad.pdf