name: Build PDF DOOM (in existing cached env)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  EMSCRIPTEN_FASTCOMP_BRANCH: "1.38.10"
  PYTHON_VERSION: 3.11

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Restore Python Dependencies Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache-${{ hashFiles('requirements.txt') }}

    - name: Install Python Dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Restore Fastcomp Cache
      id: fastcomp-cache
      uses: actions/cache@v3
      with:
        path: fastcomp/build
        key: fastcomp-build-${{ env.EMSCRIPTEN_FASTCOMP_BRANCH }}

    - name: Download DOOM WAD
      run: |
        if [ ! -f "doomgeneric/doom1.wad" ]; then
          wget "https://distro.ibiblio.org/slitaz/sources/packages/d/doom1.wad" -O "doomgeneric/doom1.wad"
        fi

    - name: Build Project
      run: |
        source .venv/bin/activate
        source ./emsdk_env.sh
        export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
        export PATH="/usr/lib/ccache:$PATH"
        
        if [[ ! -f "out/compiled.js" || \
              "out/compiled.js" -ot "doomgeneric/doom1.wad" || \
              "out/compiled.js" -ot "pre.js" || \
              "out/compiled.js" -ot "doomgeneric/doomgeneric.js" ]]; then
              
          emmake make -C doomgeneric -f Makefile.pdfjs -j$(nproc)
          mkdir -p out
          cp web/* out/

          python3 embed_file.py file_template.js doomgeneric/doom1.wad out/data.js
          cat pre.js out/data.js doomgeneric/doomgeneric.js > out/compiled.js
          cat pre.js file_template.js doomgeneric/doomgeneric.js > out/compiled_nowad.js

          python3 generate.py out/compiled.js out/doom.pdf
          python3 generate.py out/compiled_nowad.js out/doom_nowad.pdf
          
        else
          echo "No changes detected. Skipping build."
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pdf-doom
        path: |
          out/doom.pdf
          out/doom_nowad.pdf

    - name: Check Output Sizes
      run: ls -lh out/*.pdf
